version: '3.4'

services:
  crawler:
    image: ${DOCKER_REGISTRY-}crawler
    build:
      context: .
      dockerfile: Crawler/Dockerfile

  chelhackweb:
    image: ${DOCKER_REGISTRY-}chelhackweb
    build:
      context: .
      dockerfile: ChelHackWeb/Dockerfile


  chalhackapi:
    image: ${DOCKER_REGISTRY-}chalhackapi
    build:
      context: .
      dockerfile: ChelHackApi/Dockerfile

