version: '3.4'

networks:
  chelhack-net:
    driver: bridge

volumes:
  dbdata:
  images:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH-/var}/images
      o: bind

services:
  crawler:
    container_name: chelhack_crawler
    image: ${DOCKER_REGISTRY-}crawler
    environment:
      - ConnectionStrings__GoodsDatabase="mongodb://chelhack:chelhackmegapass2019@mongo:27017/eshop?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000"
    build:
      context: .
      dockerfile: Crawler/Dockerfile
    volumes:
      - images:/app/images
    networks:
      - chelhack-net

  chelhackweb:
    container_name: chelhack_web
    image: ${DOCKER_REGISTRY-}chelhackweb
    build:
      context: .
      dockerfile: ChelHackWeb/Dockerfile
    volumes:
      - images:/app/wwwroot/images:ro
    networks:
      - chelhack-net


  chalhackapi:
    container_name: chelhack_api
    image: ${DOCKER_REGISTRY-}chelhackapi
    environment:
      - ConnectionStrings__GoodsDatabase="mongodb://chelhack:chelhackmegapass2019@mongo:27017/eshop?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000"
    build:
      context: .
      dockerfile: ChelHackApi/Dockerfile
    networks:
      - chelhack-net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: eshop
      MONGO_INITDB_ROOT_USERNAME: chelhack
      MONGO_INITDB_ROOT_PASSWORD: chelhackmegapass2019
    volumes:
      - dbdata:/data/db

