version: '3.7'

networks:
  chelhack-net:
    driver: overlay

volumes:
  dbdata:
  images:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH-/home/vmadmin}/images
      o: bind

services:
  crawler:
    image: ${DOCKER_REGISTRY-}crawler
    environment:
      - ConnectionStrings__GoodsDatabase="mongodb://chelhack:chelhackmegapass2019@mongo:27017/eshop?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000"
    volumes:
      - images:/app/images
    networks:
      - chelhack-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  chelhackweb:
    container_name: chelhack_web
    image: ${DOCKER_REGISTRY-}chelhackweb
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    ports:
      - "80:80"
    volumes:
      - images:/app/wwwroot/images:ro
    networks:
      - chelhack-net
    deploy:
      replicas: 3
      restart_policy:
        condition: any

  chalhackapi:
    container_name: chelhack_api
    image: ${DOCKER_REGISTRY-}chelhackapi
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=4431
      - ConnectionStrings__GoodsDatabase="mongodb://chelhack:chelhackmegapass2019@mongo:27017/eshop?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000"
    ports:
      - "81:80"
    networks:
      - chelhack-net
    deploy:
      replicas: 3
      restart_policy:
        condition: any
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: eshop
      MONGO_INITDB_ROOT_USERNAME: chelhack
      MONGO_INITDB_ROOT_PASSWORD: chelhackmegapass2019
    volumes:
      - dbdata::/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any